### ISSUE TITLE
Add style linting to TravisCI

### ISSUE THREAD

**Issue by jdm** [servo/servo-starters#15]
@mfeckie presumably started using a JS linter in #14. We should enforce that for all PRs using Travis. Could you elaborate on the tools, @mfeckie?

**Comment by mfeckie** [comment]
I don't think this repo is currently getting CI'd with Travis is it?

**Comment by mfeckie** [comment]
I basically just used built in tools in my text editor, but I think it would be good to formalise an approach.  From my perspective, the stuff here is pretty barebones (which is totally reasonable).  Happy to do some work on adding some CI goodness, though it may make the process more complex.

**Comment by jdm** [comment]
Right, I propose adding CI :)

**Comment by mfeckie** [comment]
@jdm Will take a look tonight at getting something sensible, but minimally complex sorted
