### ISSUE TITLE
List of "potentially open issues" should be based on last modification time, not creation

### ISSUE THREAD

**Issue by jdm** [servo/servo-starters#2]
Issues like https://github.com/servo/servo/issues/6888 appear there even thought there's been activity quite recently.

**Comment by edunham** [comment]
According to https://developer.github.com/v3/issues/ , this will probably be a matter of changing the `created` parameter to `updated` in the `getPotentiallyOpenIssues` and `getOoenIssues` functions in `site.js`

**Comment by mfeckie** [comment]
@jdm Can this issue be closed now?

**Comment by jdm** [comment]
Yes!
