### ISSUE TITLE
"Mentored" tag wasn't clear to me

### ISSUE THREAD

**Issue by jsanders** [servo/servo-starters#25]
This might just be a personal problem, so feel free to close this, but whereas the "Good first PR" tag sent me in the right direction, I wasn't sure what to make of the "Mentored" tag. I thought maybe there was a mentorship process that those were a part of, but it sounds like that's not the case.

I found #1, but I'm not sure where the terminology originally comes from.

**Comment by jdm** [comment]
"Mentored" is an attempt to communicate the concept of:
- not necessarily appropriate for a brand new contributor
- has a mentor attached to it
- could lie anywhere along the spectrum of "good second PR" all the way to "challenging/lots of work, but we'll help you through it"

I haven't come up with a better name than Mentored yet; perhaps there's a place that we could spell this out on the page itself.

**Comment by jsanders** [comment]
@jdm: Thanks for the thought process. Are mentors being attached to these already? I think an explanation of the tags somewhere on the main page would have definitely made things more obvious to me.

**Comment by jdm** [comment]
Yes, the tag is added when a mentor volunteers.

**Comment by jsanders** [comment]
@jdm: Neat, I didn't realize that. It hasn't been too clear on a few of the "E less-easy" issues I've looked at exactly who volunteered as a mentor, is it usually just the issue owner unless someone else has spoken up?

**Comment by edunham** [comment]
@jsanders Thanks for the feedback! I agree, we really should make it clearer what the tags mean. 

As a starting point, https://github.com/servo/servo/wiki/Tag-label-names-and-definitions exists, but needs to be updated.

**Comment by jsanders** [comment]
@edunham: Thanks for the link! I hadn't actually come across that. Updating that would be great. It sounds like there's at least an informal mentorship process going on – maybe spelling out how that's meant to work somewhere on the wiki would be nice too. I'd love to volunteer to write this stuff up (either on the wiki or as part of servo-starters somewhere), but I'm not sure I know what to write.

**Comment by edunham** [comment]
Yeah, I'm not sure either :) 

I've added it to the Servo meeting agenda, so I'll get back to you within 2 weeks on what the team thinks. Just for future reference, do you recall the order of where you looked for the information when you felt confused about the tag? I'd like to make sure that once the docs get written, they end up in a place that'll be relatively easy to find.

**Comment by jsanders** [comment]
@edunham: To the best of my recollection: 1. Looked around servo-starters site for explanation of tags, 2. Searched servo wiki for things like "mentor", etc. 3. Searched servo codebase for same, 4. Searched servo-starters codebase, 5. Found commit introducing tag mapping, and tried to track down the reasoning, 6. Asked on #servo.
