### ISSUE TITLE
Make it possible to add non-servo repos to this app

### ISSUE THREAD

**Issue by Manishearth** [servo/servo-starters#39]
I'd like to add https://github.com/rust-lang-nursery/rustfmt/ to this (to infuse more new contributors into rustfmt). However, it uses a different tagging system (`easy` instead of `E-easy`), and isn't under the servo org.

As it stands this app searches for all appropriately tagged issues under the servo org, and sorts them. 

We should make it so that besides doing this, you can also add repos in other orgs and specify what their easy label is.

**Comment by jdm** [comment]
I'm not super interested in adding non-servo repositories to the starters.servo.org instance of this tool. I'd rather make the list of repositories and labels configurable and run separate instances.

**Comment by Manishearth** [comment]
I discussed this with folks at London, not sure if I mentioned it to you: Basically, right now we have a surplus of folks looking for easy bugs to work on, and Servo is known for this. I wanted to temporarily piggyback on it so that rustfmt can get some new contributors, and move on from there to have a starters.rlo. Right now Rust isn't known for easy bug mentoring, so this will help us bootstrap it.

**Comment by jdm** [comment]
I'm still unconvinced. I think the result will confuse people who are interested in contributing to Servo.

**Comment by Manishearth** [comment]
Fair.
