### ISSUE TITLE
It's mine, I made a PR for the issue.

### ISSUE THREAD

**Issue by Coder206** [servo/servo-starters#40]
I noticed a few issues I am actively working on are labelled as "Potentially Open Issues" based on the issue's post last message. However, mine are seen to be more active in the PR. I was thinking it would be great to take this into consideration. Perhaps @highfive can add a tag to an issue saying PR submitted? (this could also help the Servo team sort and track the progress issues more easily)

**Comment by jdm** [comment]
Currently this is a manual process - if there is a PR that is taking longer than expected (ie. longer than the period of silence which marks an issue as "potentially available"), we add the `C-has-open-PR` label to the issue which removes it form the "potentially available" list. Doing this automatically when a PR is opened might be beneficial.

**Comment by jdm** [comment]
That being said, it would make more sense to file that task in the highfive repository, since that's where the work would be done.

**Comment by Coder206** [comment]
@jdm Would you prefer to close this one in favor of opening it in highfive?

**Comment by jdm** [comment]
Yes please!
