### ISSUE TITLE
Link to the source

### ISSUE THREAD

**Issue by jdm** [servo/servo-starters#7]
It's hard to find the relationship between the rendered page and this repository.

**Comment by edunham** [comment]
All this needs is for someone to hardcode the https://github.com/servo/servo-starters URL in a link at the bottom of index.html. Extra credit, use a pretty ribbon from  https://github.com/blog/273-github-ribbons instead.

**Comment by mfeckie** [comment]
@edunham & @jdm I'm happy to pick this up
