### ISSUE TITLE
Allow filtering by language

### ISSUE THREAD

**Issue by jdm** [servo/servo-starters#8]
Isolating the ones that require python vs. rust would be a good start.

**Comment by KiChjang** [comment]
This sounds like the issues themselves need to be tagged with the appropriate language.

**Comment by jdm** [comment]
We use the L-python tag to indicate python issues, and the rest (in servo/servo) can be assumed to require Rust.

**Comment by edunham** [comment]
I'd say assume Rust unless there's the `L-python` tag or the issue is part of a shortlist of Python project repos such as highfive. Could do similar with a `webdev` tag.

**Comment by jdm** [comment]
Fixed by #26.
